version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22 # Specify your Node.js version
    commands:
      - echo "Installing dependencies for Strapi CMS"
      - cd apps/strapi-cms
      - npm install

  build:
    commands:
      - echo "Building the Strapi CMS application"
      - npm run build

artifacts:
  files:
    - '**/*'