version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies for Strapi CMS"
      - npm install
      
  build:
    commands:
      - echo "Building the Strapi CMS application"
      - npm run build
  post_build:
    commands:
      - echo "Post-build phase completed"
      - rm -rf node_modules
artifacts:
  files:
    - '**/*'
